import { KPIData, OrderItem, ReorderItem, StockAlert, InventoryItem, InvoiceItem, MarketplaceItem, DetailedOrder, SnoonuOrder } from "./types";

export const KPI_STATS: KPIData[] = [
  {
    label: "Total Cash Inflow",
    value: "QAR 45,200",
    icon: "payments",
    trend: 12.5,
    trendLabel: "from last month",
    isPositive: true,
  },
  {
    label: "Operational Costs",
    value: "QAR 12,800",
    icon: "trending_down",
    trend: 4.2,
    trendLabel: "cost savings",
    isPositive: true, 
    iconColorClass: "text-green-600",
  },
  {
    label: "Pending Orders",
    value: "8",
    icon: "pending_actions",
    trend: 0,
    trendLabel: "",
    isPositive: true,
    subtext: "3 arriving today",
  },
  {
    label: "Inventory Value",
    value: "QAR 15,600",
    icon: "inventory",
    trend: 0,
    trendLabel: "",
    isPositive: true,
    subtext: "Updated 2 hours ago",
  },
];

export const LIVE_SNOONU_ORDERS: SnoonuOrder[] = [
  {
    id: "#9921",
    customerName: "Fatima A.",
    items: "2x Chicken Machboos, 1x Fattoush",
    total: "QAR 85.00",
    status: "New",
    timeElapsed: "2m ago",
    driverStatus: "Searching for driver...",
  },
  {
    id: "#9920",
    customerName: "Mohammed S.",
    items: "1x Mixed Grill Platter (L)",
    total: "QAR 120.00",
    status: "Preparing",
    timeElapsed: "12m",
    driverStatus: "Driver arriving in 5m",
  },
  {
    id: "#9919",
    customerName: "Sarah J.",
    items: "3x Umm Ali, 2x Karak Tea",
    total: "QAR 45.00",
    status: "Ready",
    timeElapsed: "18m",
    driverStatus: "Driver waiting at pickup",
  },
  {
    id: "#9918",
    customerName: "Khalid M.",
    items: "1x Lamb Chops, 1x Hummus",
    total: "QAR 95.00",
    status: "Preparing",
    timeElapsed: "25m",
    driverStatus: "Driver assigned",
    isLate: true,
  }
];

export const REORDER_ITEMS: ReorderItem[] = [
  {
    id: "1",
    name: "Premium Napkins",
    image: "https://images.unsplash.com/photo-1583947582386-b51347043b35?auto=format&fit=crop&q=80&w=200",
    suggestion: "Suggested: 50 boxes",
    price: "QAR 120.00",
    lastOrdered: "Last ordered 3 days ago",
    badges: [
      {
        text: "High Velocity",
        colorClass: "text-primary",
        bgClass: "bg-primary/10",
      },
    ],
  },
  {
    id: "2",
    name: "Extra Virgin Olive Oil",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd391f?auto=format&fit=crop&q=80&w=200",
    suggestion: "Suggested: 10 Liters",
    price: "QAR 85.50",
    lastOrdered: "Last ordered 7 days ago",
  },
  {
    id: "3",
    name: "Roma Tomatoes",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=200",
    suggestion: "Suggested: 20 kg",
    price: "QAR 45.00",
    lastOrdered: "Last ordered 1 day ago",
    badges: [
      {
        text: "Seasonal Price Drop",
        colorClass: "text-amber-600",
        bgClass: "bg-amber-50 dark:bg-amber-900/20",
      },
    ],
  },
];

export const INCOMING_ORDERS: OrderItem[] = [
  {
    id: "101",
    supplier: "Supplier A",
    status: "Out for Delivery",
    orderNumber: "Order #1234",
    category: "Fresh Produce",
    eta: "ETA: 2:00 PM Today",
    progress: 85,
  },
  {
    id: "102",
    supplier: "Supplier B",
    status: "Processing",
    orderNumber: "Order #1235",
    category: "Dry Goods",
    eta: "Est: Tomorrow",
  },
  {
    id: "103",
    supplier: "Supplier C",
    status: "Received",
    orderNumber: "Order #1230",
    category: "Beverages",
    isCompleted: true,
  },
];

export const STOCK_ALERTS: StockAlert[] = [
  {
    id: "s1",
    name: "Tomato Paste",
    quantity: "3 cans left",
    severity: "high",
  },
  {
    id: "s2",
    name: "Flour (AP)",
    quantity: "2 bags left",
    severity: "medium", 
  },
  {
    id: "s3",
    name: "Paper Cups",
    quantity: "15 sleeves left",
    severity: "low",
  },
];

export const INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "inv1",
    name: "San Marzano Tomatoes",
    sku: "TOM-CANNED-28",
    category: "Pantry",
    stockLevel: 12,
    reorderPoint: 20,
    maxStock: 100,
    unit: "Cans (2.5kg)",
    status: "Low Stock",
  },
  {
    id: "inv2",
    name: "Extra Virgin Olive Oil",
    sku: "OIL-EVOO-5L",
    category: "Oils & Vinegars",
    stockLevel: 48,
    reorderPoint: 10,
    maxStock: 60,
    unit: "Bottle (5L)",
    status: "In Stock",
  },
  {
    id: "inv3",
    name: "Eco-Friendly Napkins",
    sku: "PAP-NAP-ECO",
    category: "Consumables",
    stockLevel: 1200,
    reorderPoint: 500,
    maxStock: 2000,
    unit: "Case (1000pc)",
    status: "In Stock",
  },
  {
    id: "inv4",
    name: "Basmati Rice",
    sku: "GRN-RICE-20KG",
    category: "Dry Goods",
    stockLevel: 2,
    reorderPoint: 5,
    maxStock: 20,
    unit: "Sack (20kg)",
    status: "Critical",
  },
  {
    id: "inv5",
    name: "Takeout Containers (Large)",
    sku: "PKG-BOX-L",
    category: "Packaging",
    stockLevel: 350,
    reorderPoint: 100,
    maxStock: 500,
    unit: "Box (50pc)",
    status: "In Stock",
  },
];

export const INVOICES: InvoiceItem[] = [
  {
    id: "inv-001",
    invoiceNumber: "#INV-001",
    dateIssued: "Oct 24, 2023",
    supplierName: "TechSupply Co.",
    amount: "QAR 1,200.00",
    dueDate: "Oct 30, 2023",
    status: "Pending",
  },
  {
    id: "inv-002",
    invoiceNumber: "#INV-002",
    dateIssued: "Oct 20, 2023",
    supplierName: "Logistics Partners",
    amount: "QAR 450.00",
    dueDate: "Oct 28, 2023",
    status: "Paid",
  },
  {
    id: "inv-003",
    invoiceNumber: "#INV-003",
    dateIssued: "Sep 15, 2023",
    supplierName: "Office Depot",
    amount: "QAR 800.00",
    dueDate: "Sep 30, 2023",
    status: "Overdue",
  },
  {
    id: "inv-004",
    invoiceNumber: "#INV-004",
    dateIssued: "Oct 29, 2023",
    supplierName: "CleanSpace LLC",
    amount: "QAR 320.00",
    dueDate: "Nov 05, 2023",
    status: "Pending",
  },
  {
    id: "inv-005",
    invoiceNumber: "#INV-005",
    dateIssued: "Oct 10, 2023",
    supplierName: "CloudServe Inc",
    amount: "QAR 2,150.00",
    dueDate: "Oct 15, 2023",
    status: "Paid",
  },
];

export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: "m1",
    name: "Fresh Avocados (Hass)",
    category: "Produce",
    supplier: "Green Valley Farms",
    price: "QAR 45.00",
    unit: "Case (48ct)",
    image: "https://images.unsplash.com/photo-1523049673856-356964858d45?auto=format&fit=crop&q=80&w=400",
    rating: 4.8,
    reviews: 124,
    isOrganic: true,
  },
  {
    id: "m2",
    name: "Angus Beef Patties",
    category: "Meat & Poultry",
    supplier: "Prime Meats Ltd",
    price: "QAR 120.00",
    unit: "Box (20lb)",
    image: "https://images.unsplash.com/photo-1603048297172-c92544798d5e?auto=format&fit=crop&q=80&w=400",
    rating: 4.9,
    reviews: 89,
    discount: "10% OFF",
  },
  {
    id: "m3",
    name: "Whole Milk Mozzarella",
    category: "Dairy",
    supplier: "Happy Cow Dairy",
    price: "QAR 32.50",
    unit: "Block (5lb)",
    image: "https://images.unsplash.com/photo-1624806992066-5d544f4d22f8?auto=format&fit=crop&q=80&w=400",
    rating: 4.6,
    reviews: 56,
    isLocal: true,
  },
  {
    id: "m4",
    name: "Sourdough Bread Loaves",
    category: "Bakery",
    supplier: "Artisan Bakes",
    price: "QAR 5.00",
    unit: "Loaf",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400",
    rating: 4.9,
    reviews: 210,
    isLocal: true,
  },
  {
    id: "m5",
    name: "Jasmine Rice (Premium)",
    category: "Dry Goods",
    supplier: "Global Grains",
    price: "QAR 48.00",
    unit: "Bag (50lb)",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400",
    rating: 4.7,
    reviews: 45,
  },
  {
    id: "m6",
    name: "Atlantic Salmon Fillets",
    category: "Seafood",
    supplier: "Ocean Fresh",
    price: "QAR 18.50",
    unit: "Per lb",
    image: "https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&q=80&w=400",
    rating: 4.8,
    reviews: 112,
  },
];

export const ALL_ORDERS: DetailedOrder[] = [
  {
    id: "ord-1001",
    orderNumber: "#ORD-8821",
    date: "Oct 24, 2023",
    supplier: "Green Valley Farms",
    status: "Delivered",
    total: "QAR 450.00",
    itemsCount: 3,
    itemsSummary: "Avocados, Romaine Lettuce, Tomatoes",
  },
  {
    id: "ord-1002",
    orderNumber: "#ORD-8822",
    date: "Oct 25, 2023",
    supplier: "Prime Meats Ltd",
    status: "Shipped",
    total: "QAR 1,250.00",
    itemsCount: 5,
    itemsSummary: "Beef Patties, Chicken Breast, Bacon...",
  },
  {
    id: "ord-1003",
    orderNumber: "#ORD-8823",
    date: "Oct 26, 2023",
    supplier: "Happy Cow Dairy",
    status: "Confirmed",
    total: "QAR 320.00",
    itemsCount: 2,
    itemsSummary: "Mozzarella, Heavy Cream",
  },
  {
    id: "ord-1004",
    orderNumber: "#ORD-8824",
    date: "Today, 9:00 AM",
    supplier: "Artisan Bakes",
    status: "Placed",
    total: "QAR 85.00",
    itemsCount: 12,
    itemsSummary: "Sourdough, Burger Buns",
  },
  {
    id: "ord-1005",
    orderNumber: "#ORD-8819",
    date: "Oct 20, 2023",
    supplier: "Ocean Fresh",
    status: "Cancelled",
    total: "QAR 0.00",
    itemsCount: 1,
    itemsSummary: "Salmon Fillets",
  },
];
